<?php
/**
 * Ecozyon Tech Theme Functions
 * Automatically generated by build-wp.js
 */

function ecozyon_enqueue_assets() {
    $theme_dir = get_template_directory_uri();
    
    wp_enqueue_style('ecozyon-style-0', $theme_dir . '/assets/index-BGDNCRQc.css', array(), null);
    wp_enqueue_script('ecozyon-script-0', $theme_dir . '/assets/About-C9EaKkDO.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-1', $theme_dir . '/assets/Accessibility-G54-whHB.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-2', $theme_dir . '/assets/Admin-Deh3-1qv.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-3', $theme_dir . '/assets/AnimatedNumber-CP4z2VAw.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-4', $theme_dir . '/assets/Assessment-Bgimu5Ne.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-5', $theme_dir . '/assets/Blog-B8sZRwxK.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-6', $theme_dir . '/assets/BlogPost-CnHQgYTo.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-7', $theme_dir . '/assets/BlogTag-Bf1O99QN.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-8', $theme_dir . '/assets/Breadcrumbs-WmPYF197.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-9', $theme_dir . '/assets/capitals-CS035f4g.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-10', $theme_dir . '/assets/Careers-DAOhGjVs.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-11', $theme_dir . '/assets/cases-CP0W8w8f.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-12', $theme_dir . '/assets/Cases-Ds_zY_ib.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-13', $theme_dir . '/assets/CaseStudy-BD7bCTTl.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-14', $theme_dir . '/assets/Changelog-CNQSo3Sm.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-15', $theme_dir . '/assets/changelog-QSGA0sYn.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-16', $theme_dir . '/assets/charts-CJpErydL.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-17', $theme_dir . '/assets/cities-zkU2hiDa.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-18', $theme_dir . '/assets/Collapse-0rfl0bLD.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-19', $theme_dir . '/assets/CommandPalette-Cxrx0sIh.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-20', $theme_dir . '/assets/Contact-BZot9W3V.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-21', $theme_dir . '/assets/Developers-CCYnqKD_.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-22', $theme_dir . '/assets/EcoGlobe-JzSP54QG.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-23', $theme_dir . '/assets/glossary-B62EuCXW.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-24', $theme_dir . '/assets/Glossary-C6TzUHZR.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-25', $theme_dir . '/assets/GridPattern-BJ5piuW9.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-26', $theme_dir . '/assets/help-6STPt2Z8.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-27', $theme_dir . '/assets/Help-DxmgZC6u.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-28', $theme_dir . '/assets/Home-DikGK28B.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-29', $theme_dir . '/assets/Impact-Ddqcfvsz.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-30', $theme_dir . '/assets/index-CP4P6BDG.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-31', $theme_dir . '/assets/integrations-C3IhrlCc.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-32', $theme_dir . '/assets/jobs-cEfOJNLm.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-33', $theme_dir . '/assets/LazyGlobes-BvUtOtfj.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-34', $theme_dir . '/assets/Legal-3JLd0mCy.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-35', $theme_dir . '/assets/Marquee-CRxTqvhn.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-36', $theme_dir . '/assets/Modal-CARTSTVq.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-37', $theme_dir . '/assets/NotFound-Dv9L4uxR.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-38', $theme_dir . '/assets/OnboardingTour-CO_jWBcL.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-39', $theme_dir . '/assets/posts-whGJ_vc6.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-40', $theme_dir . '/assets/Press-DPTAxpLC.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-41', $theme_dir . '/assets/Roi-CjP6qKJ6.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-42', $theme_dir . '/assets/rolldown-runtime-S-ySWqyJ.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-43', $theme_dir . '/assets/saved-Co1lcOC8.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-44', $theme_dir . '/assets/search-6cWwkUZE.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-45', $theme_dir . '/assets/Search-CijIeJlh.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-46', $theme_dir . '/assets/SectionNav-_v3XNv7W.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-47', $theme_dir . '/assets/Services-7WvQrNrT.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-48', $theme_dir . '/assets/Sitemap-Qv9vFv_r.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-49', $theme_dir . '/assets/SpotlightCard-Dg9h_nh9.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-50', $theme_dir . '/assets/Styleguide-RBXTySf_.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-51', $theme_dir . '/assets/Tabs-B6B1ERS8.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-52', $theme_dir . '/assets/TechMarquee-B97m9VGi.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-53', $theme_dir . '/assets/three-By1tz7Ru.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-54', $theme_dir . '/assets/TiltCard-BhdIDQF-.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-55', $theme_dir . '/assets/Tooltip-CuAgx0V9.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-56', $theme_dir . '/assets/useAllPosts-BEmJ0nzd.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-57', $theme_dir . '/assets/useDocumentMeta-DHE3D-zd.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-58', $theme_dir . '/assets/useFilteredList-BHyO6Zlt.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-59', $theme_dir . '/assets/useFocusTrap-BFeC7T00.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-60', $theme_dir . '/assets/vendor-AvONtJzz.js', array(), null, true);
    wp_enqueue_script('ecozyon-script-61', $theme_dir . '/assets/WorldGlobe-CdnD8Jdq.js', array(), null, true);
}
add_action('wp_enqueue_scripts', 'ecozyon_enqueue_assets');

// Add type="module" to JS scripts
function ecozyon_add_type_attribute($tag, $handle, $src) {
    if (strpos($handle, 'ecozyon-script') !== false) {
        $tag = '<script type="module" src="' . esc_url($src) . '"></script>';
    }
    return $tag;
}
add_filter('script_loader_tag', 'ecozyon_add_type_attribute', 10, 3);
