import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

console.log('🚀 Starting WordPress Theme Build...');

// 1. Run Vite build
console.log('📦 Building React application for SPA...');
execSync('npm run build:spa', { stdio: 'inherit' });

// Paths
const distDir = path.resolve('dist');
const distAssets = path.join(distDir, 'assets');
const wpThemeDir = path.resolve('wp-theme');
const wpAssets = path.join(wpThemeDir, 'assets');

// 2. Prepare wp-theme/assets directory
console.log('📂 Copying assets to wp-theme...');
if (fs.existsSync(wpAssets)) {
  fs.rmSync(wpAssets, { recursive: true, force: true });
}
fs.mkdirSync(wpAssets, { recursive: true });

// Copy all assets
fs.cpSync(distAssets, wpAssets, { recursive: true });

// 3. Scan for JS and CSS files to enqueue
const files = fs.readdirSync(wpAssets);
const jsFiles = files.filter(f => f.endsWith('.js'));
const cssFiles = files.filter(f => f.endsWith('.css'));

// 4. Generate functions.php
console.log('⚙️ Generating functions.php...');
let functionsPhp = `<?php
/**
 * Ecozyon Tech Theme Functions
 * Automatically generated by build-wp.js
 */

function ecozyon_enqueue_assets() {
    $theme_dir = get_template_directory_uri();
    
`;

// Enqueue CSS
cssFiles.forEach((file, index) => {
    functionsPhp += `    wp_enqueue_style('ecozyon-style-${index}', $theme_dir . '/assets/${file}', array(), null);\n`;
});

// Enqueue JS
jsFiles.forEach((file, index) => {
    // Need type="module" for Vite builds, so we'll add a filter below
    functionsPhp += `    wp_enqueue_script('ecozyon-script-${index}', $theme_dir . '/assets/${file}', array(), null, true);\n`;
});

functionsPhp += `}
add_action('wp_enqueue_scripts', 'ecozyon_enqueue_assets');

// Add type="module" to JS scripts
function ecozyon_add_type_attribute($tag, $handle, $src) {
    if (strpos($handle, 'ecozyon-script') !== false) {
        $tag = '<script type="module" src="' . esc_url($src) . '"></script>';
    }
    return $tag;
}
add_filter('script_loader_tag', 'ecozyon_add_type_attribute', 10, 3);
`;

fs.writeFileSync(path.join(wpThemeDir, 'functions.php'), functionsPhp);

console.log('✅ WordPress theme generation complete!');
console.log('📁 The "wp-theme" directory is ready for deployment.');
