name: Deploy to WordPress.com
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build WordPress Theme
        run: npm run build:wp

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: wp-theme/
